### ISSUE TITLE
Build Environment variables problem

### ISSUE THREAD

**Issue by uzairoffical** [bradtraversy/github-finder#3]
Hello Bradtraversy,
First of all , I personally thank you for your wonderfull and easy to learn tutorial series. Currently complete follow steps for making github finder app. When I try to make build and serve -s build at local computer Enviroment variable are undefined 
![Screenshot from 2019-09-10 11-42-09](https://user-images.githubusercontent.com/55087417/64590073-1e79ef80-d3c0-11e9-8dcc-8df54feb8a3b.png) 

And when I deploy on netlify account , same problem occurs there.

![Screenshot from 2019-09-10 11-44-38](https://user-images.githubusercontent.com/55087417/64590208-6f89e380-d3c0-11e9-877f-80845009e245.png)
![Screenshot from 2019-09-10 11-45-45](https://user-images.githubusercontent.com/55087417/64590256-921bfc80-d3c0-11e9-90c9-127f615ba292.png)

**Comment by andyaspel** [comment]
did you close server after making .env.local file?
I had same problem, did not listen to Brad telling us to do this.
thought saving and letting react re-compile was enougth.
looked up info on www tried this tried that nothing worked
So i deleted .env.local file
restart server ->check if all still working
ok still works
stopped server
then I remade .env.local file and saved
start server -> and yes it worked.
Hope this helps, took me an hour to sort out.
success Andy

**Comment by uzairoffical** [comment]
I resolve this issue by using .env.product file and defining variable on with prefix of 'REACT_APP_*'
